AppointmentFn:
  handler: lambdas/appointment/index.handler
  name: AppointmentFn
  description: Funci贸n lambda con endpoints http.
  timeout: 30
  package:
    include:
      - lambdas/appointment/**
    exclude:
      - lambdas/**
  layers:
    - !Ref LambdaCoreLambdaLayer
  role: !GetAtt SchedulingLambdaRole.Arn
  environment:
    TABLE_NAME: MedicalScheduling
    APPOINTMENT_TOPIC_ARN: !Ref AppointmentTopic
  events:
    - http:
        path: /appointment
        method: post
        cors: true
    - http:
        path: /appointment
        method: get
        cors: true
    - sqs:
        arn:
          Fn::GetAtt: [AppointmentQueue, Arn]
AppointmentPeFN:
  handler: lambdas/appointment-pe/index.handler
  name: AppointmentPeFN
  description: Funci贸n lambda.
  timeout: 30
  layers:
    - !Ref LambdaCoreLambdaLayer
    - !Ref MysqlCoreLambdaLayer
  role: !GetAtt SchedulingLambdaRole.Arn
  package:
    include:
      - lambdas/appointment-pe/**
    exclude:
      - lambdas/**
  environment:
    DB_HOST: 0.tcp.sa.ngrok.io
    DB_PORT: 15428
    DB_NAME: medical
    DB_USER: user
    DB_PASSWORD: p@ssworD
  events:
    - sqs:
        arn:
          Fn::GetAtt: [SqsPE, Arn]

AppointmentClFN:
  handler: lambdas/appointment-cl/index.handler
  name: AppointmentClFN
  description: Funci贸n lambda.
  timeout: 30
  layers:
    - !Ref LambdaCoreLambdaLayer
    - !Ref MysqlCoreLambdaLayer
  role: !GetAtt SchedulingLambdaRole.Arn
  package:
    include:
      - lambdas/appointment-cl/**
    exclude:
      - lambdas/**
  environment:
    DB_HOST: 0.tcp.sa.ngrok.io
    DB_PORT: 15428
    DB_NAME: medical
    DB_USER: user
    DB_PASSWORD: p@ssworD
  events:
    - sqs:
        arn:
          Fn::GetAtt: [SqsCL, Arn]
  
OpenApiFN:
  handler: docs/index.handler
  name: OpenApiFN
  description: Sirve la documentaci贸n OpenAPI
  package:
    include:
      - docs/**
    exclude:
      - lambdas/**
  events:
    - http:
          path: docs
          method: get
          cors: true
    - http:
        path: docs/openapi.yml
        method: get
        cors: true