LambdaCore:
  path: _layers/lambda-core
  name: LambdaCore
  description: Core dependencies
  compatibleRuntimes:
    - nodejs20.x
MysqlCore:
  path: _layers/mysql-core
  name: MysqlCore
  description: Mysql dependencies
  compatibleRuntimes:
    - nodejs20.x
