name: Desarrollo

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Print current working directory
        uses: actions/checkout@v4

      - name: Install Dependencies in _layers/lambda-core/nodejs
        run: |
          cd _layers/lambda-core/nodejs
          npm install
      - name: Install Dependencies in _layers/mysql-core/nodejs
        run: |
          cd _layers/mysql-core/nodejs
          npm install

      - name: List files in directory
        run: |
          ls -R

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependencies
        run: npm ci

      - name: Deploy with Serverless
        uses: serverless/github-action@v3.2
        with:
          args: >
            deploy --verbose --stage dev

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV  }}
